version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: api/dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database

  login:
    container_name: login
    build:
      context: .
      dockerfile: login/dockerfile
    ports:
      - 8081:8080
    depends_on:
      - database

  web:
    container_name: web
    build:
      context: ./web/
      dockerfile: Dockerfile
    ports:
      - 8082:8080

  database:
    container_name: database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_EXTENSION=uuid-ossp

  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - login
