FROM golang:1.18-buster AS build

WORKDIR /app

ENV GO111MODULE=on

COPY ./login ./login
COPY ./shared ./shared

RUN cd shared && go mod download

RUN cd login && go mod download
RUN cd login && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -mod=mod -o /go/bin/login main.go

FROM alpine

COPY --from=build /go/bin/login /app/
COPY --from=build /app/login/.env /app/.env
COPY --from=build /app/shared/.env /app/.env

WORKDIR /app

CMD ["./login"]
