FROM golang:1.18-buster AS build

WORKDIR /app

ENV GO111MODULE=on

COPY ./login ./login
COPY ./shared ./shared

RUN cd shared && go mod download

RUN cd login && go mod download
RUN cd login && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -mod=mod -o /go/bin/start main.go

FROM alpine

WORKDIR /app

COPY --from=build /go/bin/start /app/login/
COPY --from=build /app/login/.env/login.docker.env /app/login/.env/
COPY --from=build /app/login/dockerfile-run.sh /app/
COPY --from=build /app/shared/.env/shared.docker.env /app/shared/.env/
COPY --from=build /app/shared/templates /app/shared/templates

ENV ORREVUA_DEPLOY_ENV=docker

RUN chmod +x dockerfile-run.sh
ENTRYPOINT [ "./dockerfile-run.sh" ]